import p1_img from './product_1.webp'
import p2_img from './product_2.webp'
import p3_img from './product_3.webp'

export const all_product = [
    {
        id: 1,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 2,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 3,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 4,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 5,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 6,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 7,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 8,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 9,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 10,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 11,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 12,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 13,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 14,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 15,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 16,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 17,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 18,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 19,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 20,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 21,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 22,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 23,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 24,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 25,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 26,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 27,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 28,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 29,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 30,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 31,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 32,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },
    {
        id: 33,
        name: "Hoodie",
        image: p1_img,
        new_price: 50.00,
        old_price: 81.50,
        category: "women",
    },
    {
        id: 34,
        name: "Trening pants",
        image: p2_img,
        new_price: 45.00,
        old_price: 88.99,
        category: "men",
    },
    {
        id: 35,
        name: "Trening set",
        image: p3_img,
        new_price: 169.99,
        old_price: 259.99,
        category: "kids",
    },
    {
        id: 36,
        name: "Hoodie",
        image: p1_img,
        new_price: 69.99,
        old_price: 99.99,
        category: "women",
    },

]